version: '3.8'

services:
  backend:
    container_name: "ci_backend"
    image: backend-api-image:latest
    ports:
      - "8000:8000"
    networks:
      - backend_network

  db:
    container_name: "ci_postgres"
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - db_data_ci:/var/lib/postgresql/data
    networks:
      - backend_network

  redis:
    container_name: "ci_redis"
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - backend_network

volumes:
  db_data_ci:

networks:
  backend_network:
