"""up: fix bugs models

Revision ID: 95ed7c3653c7
Revises: abc6c5f9db39
Create Date: 2024-12-30 09:29:43.273954

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "95ed7c3653c7"
down_revision: Union[str, None] = "abc6c5f9db39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("answers", sa.Column("title_ru", sa.String(length=999), nullable=True))
    op.add_column("answers", sa.Column("title_kg", sa.String(length=999), nullable=True))
    op.drop_column("answers", "title")
    op.create_unique_constraint(None, "groups", ["title"])
    op.add_column("questions", sa.Column("title_ru", sa.String(length=999), nullable=True))
    op.add_column("questions", sa.Column("title_kg", sa.String(length=999), nullable=True))
    op.add_column("questions", sa.Column("description_ru", sa.String(), nullable=True))
    op.add_column("questions", sa.Column("description_kg", sa.String(), nullable=True))
    op.drop_column("questions", "title")
    op.drop_column("questions", "description")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "questions",
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "questions",
        sa.Column("title", sa.VARCHAR(length=999), autoincrement=False, nullable=True),
    )
    op.drop_column("questions", "description_kg")
    op.drop_column("questions", "description_ru")
    op.drop_column("questions", "title_kg")
    op.drop_column("questions", "title_ru")
    op.drop_constraint(None, "groups", type_="unique")
    op.add_column(
        "answers",
        sa.Column("title", sa.VARCHAR(length=999), autoincrement=False, nullable=True),
    )
    op.drop_column("answers", "title_kg")
    op.drop_column("answers", "title_ru")
    # ### end Alembic commands ###
